### ISSUE TITLE
Could we add a shebang line?

### ISSUE THREAD

**Issue by kseistrup** [xonixx/mdbooker#1]
Instead of invoking this utility as `awk -f mdbooker.awk`, I wonder if we could just add a shebang line:

```awk
#!/usr/bin/env -S awk -f
BEGIN {
  if (!(Repo = ENVIRON["REPO"]))
    ⋮
```

If the script is then renamed as `mdbooker` and made executable, it can be called as `mdbooker` and will use whichever flavour of `awk`  the user has in their path.

And if someone wants to use a specific flavour of AWK, they can just use the method you are suggesting in the current README: `awk -f mdbooker`

:smile:

**Comment by xonixx** [comment]
Probably, we can. However, I think I'd prefer `#!/usr/bin/awk -f` becase `env -S` is [not portable](https://stackoverflow.com/a/16365367):

> You can use /usr/bin/env -S on some versions of env to get around this, but then the script will become even less portable and break on fairly recent systems (e.g. even Ubuntu 16.04 if not later).

**Comment by kseistrup** [comment]
The flip side of that is that not all AWKs live in `/usr/bin`. Personally, I will be fine with `#!/usr/bin/awk -f`, though (and find it highly preferrable to the `awk -f mdbooker` invocation).

**Comment by xonixx** [comment]
Done.
